@startuml

interface Target
Class Adapter
Class Adaptee
Class Client

Client ---> Target
Adapter ---->Adaptee
Adapter ...|>Target
Interface Target{
request()
}

Class Adapter{
request()
}

Class Adaptee{
specificRequest()
}

@enduml